print("A en ASCII es igual a \"65\"\n")
print("¿Como te llamas?\n")
print("¿Como te llamas?\n")
print("A \\ B significa: el conjunto que contiene todos aquellos elementos de A que no se encuentran en B\n")
print('\0',"el caracter nulo no se muestra\n") 
print("oyes eso? \a\n")
print("La letra \'a\' en borrar se va a borra\br\n")
print("\\f se ve muy parecido\fa usar \\n\n")
print("que se ve \fparecido\f a usar  \f pero ")
print("como puedes\f ver \\f no funciona igual a \\n\n")
print("Esto se va a sobreescrbir\r")
print("con lo que pongas aquí, y así funciona \\r como el retorno de la máquina de escribir\n")
print("de ahí su nombre")
print("\\t\t es parecido a oprimir el TAB en el teclado\n")
print("y \\v\v es parecido a oprimir Enter en el teclado\vaunque más bien se parece a \\f\f")
print("\120 es igual a 80 en ASCII",'\n')
print("\x41 es igual a 65 en ASCII",'\n')
print("\u00B6 es igual a \U000000B6 \n")
print("pero \u102AF  no es igual a \U000102AF",'\n')